### ISSUE TITLE
Use ex_machina instead of fixtures

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/hades#34]
I noticed we're using fixtures in two different ways:

```elixir
  def fixture(:mentoree) do
    {:ok, mentoree} = Mentorships.create_mentoree(@create_attrs)
    mentoree
  end

  def user_fixture(attrs \\ %{}) do
    {:ok, user} =
      attrs
      |> Enum.into(%{email: FakeData.email, name: "some name", is_admin: FakeData.boolean, password: "S0m3p4ssW0rd"})
      |> Auth.signup
    user
  end
```

~Should we normalize this somehow ?~
Let's use ex_machina instead of fixtures altogether

**Comment by ccarvalho-eng** [comment]
I'd opt for using the ExMachina instead so we'll gonna have more flexibility and we'll don't need to define it in every test.

**Comment by lbighetti** [comment]
I'll setup ExMachina at #35 and starting implementing this approach

**Comment by lbighetti** [comment]
Done for Mentorees on #35 
We still need to refactor Mentors for this

**Comment by lbighetti** [comment]
This is done
