### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by lbighetti** [lbighetti/hades#41]
We need a guide to welcome contributors and PRs.

We should make it clear and easy what the process is.

**Comment by ccarvalho-eng** [comment]
We can definitely update this [code of conduct](https://www.contributor-covenant.org/version/1/2/0/code-of-conduct.html) to use in this project.

**Comment by lbighetti** [comment]
@webofbits we could definitely use that!
But that looks more like like a code of conduct.

What i meant here is: what are the steps to start contributing to this project.
Perhaps it can even be in the readme, something like: 

* Have a look at open issues
* Pick one and comment that you're taking a look
* submit a PR

What do you think ?

**Comment by lbighetti** [comment]
Attempted this at https://github.com/lbighetti/hades/pull/56, see what you think

**Comment by lbighetti** [comment]
Should be enough for now.
